import { SUPPORTED_CHAINS } from "@brillionfi/wallet-infra-sdk/dist/models";

export interface IChainSelectorProps {
  enableTestNetworks?: boolean;
  networks?: SUPPORTED_CHAINS[];
}

export const TEST_NETWORKS = [
  SUPPORTED_CHAINS.ARBITRUM_TESTNET,
  SUPPORTED_CHAINS.AVALANCHE_FUJI_TESTNET,
  SUPPORTED_CHAINS.BASE_SEPOLIA,
  SUPPORTED_CHAINS.ETHEREUM_SEPOLIA,
  SUPPORTED_CHAINS.POLYGON_AMOY,
  SUPPORTED_CHAINS.SOLANA_TESTNET,
  SUPPORTED_CHAINS.TELOS_TESTNET,
  SUPPORTED_CHAINS.TRON_TESTNET,
  SUPPORTED_CHAINS.VANAR_VANGUARD,
  SUPPORTED_CHAINS.ZILLIQA2_PROTO_TESTNET,
  SUPPORTED_CHAINS.ZILLIQA_TESTNET,
];

export const PROD_NETWORKS = [
  SUPPORTED_CHAINS.ARBITRUM,
  SUPPORTED_CHAINS.AVALANCHE,
  SUPPORTED_CHAINS.BASE,
  SUPPORTED_CHAINS.COSMOS,
  SUPPORTED_CHAINS.ETHEREUM,
  SUPPORTED_CHAINS.POLYGON,
  SUPPORTED_CHAINS.SOLANA,
  SUPPORTED_CHAINS.TELOS,
  SUPPORTED_CHAINS.TRON,
  SUPPORTED_CHAINS.VANAR,
  SUPPORTED_CHAINS.ZILLIQA,
];

export const NETWORKS = [...TEST_NETWORKS, ...PROD_NETWORKS];
